apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yjy03q9s3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yjy03q9s3-java-quarkus-gitops