apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: yjy03q9s3-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-68c237572c.nbdx.p3.openshiftapps.com/rhtap/rhtap-qe:4cf81aabe1e642307413d085a2e8c5fcc15d1278@sha256:022ffac884d681e1ff2842e6d62a01a4336f692f2c7e77f2274709310b65a8bf
        name: container-image  
